package dev.pradeep.OnTravelsAssignment.Controller;

import dev.pradeep.OnTravelsAssignment.Entity.User;
import dev.pradeep.OnTravelsAssignment.Services.UserService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

/*
    controller to handle users
 */

@RestController
@RequestMapping("/api/users")
public class UserController {

    private final UserService userService;

    public UserController(UserService userService) {
        this.userService = userService;
    }

    /*
        POST /save_user
        saves the user in database
        ex:

            {
                "name": "vinyak",
                "age": 12
            }

        note - Id is autogenerated
     */
    @PostMapping("/save_user")
    public ResponseEntity<?> saveUser(@RequestBody User user) {
        try {
            userService.addUser(user);
            return ResponseEntity.status(HttpStatus.CREATED).body("Successfully added user");
        } catch (Exception e) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(e.getMessage());
        }
    }

    /*
        fetches all the users in database
     */
    @GetMapping("/find_users")
    public ResponseEntity<List<User>> users() {
        return ResponseEntity.status(200).body(userService.fetchAllUsers());
    }

    /*
        delete a particular user in database
        ex DELETE /delete_user/{userId}
        deletes the user from the database
     */
    @DeleteMapping("/delete_user/{id}")
    public ResponseEntity<?> deleteUser(@PathVariable String id){
        return ResponseEntity.ok(userService.deleteUser(id));
    }

    /*
        delete all users
     */
    @DeleteMapping("/delete_users")
    public ResponseEntity<?> deleteUsers() {
        userService.deleteAllUsers();
        return ResponseEntity.status(HttpStatus.NO_CONTENT).build();
    }
}
